### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by tuxillo** [six-group/haproxy-operator#36]
Hi,

Need to do some HAProxy deployments and I was wondering how mature this was.

Thanks

**Comment by m-terra** [comment]
hi @tuxillo 

yes, absolutely. it is used for a big number of instances for about a year now.

cheeers, andy

**Comment by tuxillo** [comment]
Another question (sorry for going off topic on this issue). Where do you define the Service itself? For example, I would like to have a load balancer attached to a specific Instance since I'm running in EKS, hence I need annotations.
