### ISSUE TITLE
feature: add check-sni server option

### ISSUE THREAD

**Issue by mike-code** [six-group/haproxy-operator#46]
It would be beneficial to add the [check-sni](https://docs.haproxy.org/2.9/configuration.html#5.2-check-sni) backend option to the `Backend` resource, perhaps as a key in `servers.*.check`.

Motivation: without this option, the health check fails with `Layer6 invalid response, info: "SSL handshake failure"` error message. I noticed that it doesn't happen with every server that expects a TLS connection, but it bit me this one time.

**Comment by m-terra** [comment]
hi @mike-code

thank you very much for your suggestions. we will have a look at it.

meanwhile, PRs are highly appreciated.

cheers, andy

**Comment by m-terra** [comment]
added with v1.0.6
