### ISSUE TITLE
Question: replacement for ingress controller or rather complementing it?

### ISSUE THREAD

**Issue by mike-code** [six-group/haproxy-operator#64]
So I was thinking (based on how you use it internally) if the instances from the operator may be used as ingress controller(s). 

Due to the fact that `Backend` crd does not have properties that bind it to k8s `Services` directly, would you still use it as ingress controller and set domains `svc.namespace.cluster.domain` or the use-case is that the haproxy instances here act as "regular" cluster services?

**Comment by m-terra** [comment]
hi @mike-code 

it can and is used as ingress controller and was designed with this puprose in mind. the backend server can by any host, regardless of whether it's an internal service or and external one.

cheers, andy
