### ISSUE TITLE
No chance of managing the service type of the Instance

### ISSUE THREAD

**Issue by icamacho1** [six-group/haproxy-operator#75]
I haven't found a way of setting the Service type of the instance to be LoadBalancer (so that I can use it as a ingress). Is there any way to actually do this.

I found that in: `controllers/instance/service.go` you have the definition of the instance Service.
```go
	service := &corev1.Service{
		ObjectMeta: metav1.ObjectMeta{
			Name:      utils.GetServiceName(instance),
			Namespace: instance.Namespace,
		},
	}
```

But I see nowhere in that file that the spec type is set (like):
```go
if serviceType != nil && *serviceType == constants.TypeLoadBalancer {
    service.Spec = corev1.ServiceSpec{
        Type: corev1.ServiceTypeLoadBalancer,
    }
}
```

I'm nowhere an expert in k8s (just toying around) and I may very well be saying something barbaric 😂.

Edit: added a [PR](https://github.com/six-group/haproxy-operator/pull/77).

**Comment by m-terra** [comment]
PR has been merged. Thank you very much for your contribution.

There is one more feature coming in the next days and then we will release it.
